
INPUT_DIR: "../Simulated-Data/Data"

FILE_DATA: ["sysmex_X","sysmex_X_denoised"]
FILE_LABEL: "../Simulated-Data/Data/sysmex_y.csv"

GROUP: ["Asthma","EosinophilSerumCount"] # "all"

OUTPUT_DIR: "../Classification_Benchmark_Data/Sysmex_Analysis"

# MODE: "Classification" # "Classification"/"Regression"

FEATURE_SELECTION: ["stability"] #,"boruta", "sklearn_RFE"
ESTIMATOR: ["RFC", "LR_l2"]

METHODS: ["linear_model"] #, "LR_l1", "LR_l2", "SGDC_l1", "SGDC_l2", , "DT", , "ET",  , "CNB", "SVM_l1", "SVM_l2", "KNN"] #Classification ["LR_l1", "LR_l2", "LR_elasticnet", "SGD_l1", "SGD_l2", "SGD_elasticnet", "DT", "RFC", "ET", "ADB", "GBTC", "GNB", "CNB", "SVM_l1", "SVM_l2", "KNN", "INGOT"]
#"GNB"

OPTIMIZATION: "GridSearchCV" # 'GridSearchCV', 'RandomizedSearchCV', 'BayesSearchCV' and "None"

SEED: 1234
# TODO multiclass