estimator: "LR_elasticnet"

Feature_Selection:
  # Methods included in the Scikit-Learn Package
  # For further information, please refer to https://scikit-learn.org/stable/

  VarianceThreshold:
    module: sklearn.feature_selection
    name: VarianceThreshold
    params:
      threshold: 0.16

  SelectKBest:
    module: sklearn.feature_selection
    name: SelectKBest
    params:
      k: 10

  SelectPercentile:
    module: sklearn.feature_selection
    name: SelectPercentile
    params:
      percentile: 20

  SelectFpr:
    module: sklearn.feature_selection
    name: SelectFpr
    params:
      alpha: 0.05

  SelectFdr:
    module: sklearn.feature_selection
    name: SelectFpr
    params:
      alpha: 0.05

  SelectFwe:
    module: sklearn.feature_selection
    name: SelectFpr
    params:
      alpha: 0.05

  RFE:
    module: sklearn.feature_selection
    name: RFE
    params:
      n_features_to_select: 0.2
      step: 1

  RFECV:
    module: sklearn.feature_selection
    name: RFECV
    params:
      step: 1
      min_features_to_select: 1
      scoring: "accuracy"
      cv: 5
      n_jobs: -1
      verbose: 1

  SelectFromModel:
    module: sklearn.feature_selection
    name: SelectFromModel
    params:
      threshold: "mean"

  SequentialFeatureSelectorForward:
    module: sklearn.feature_selection
    name: SequentialFeatureSelector
    params:
      n_features_to_select: 0.2
      direction: "forward"
      cv: 5

  SequentialFeatureSelectorBackward:
    module: sklearn.feature_selection
    name: SequentialFeatureSelector
    params:
      direction: "backward"
      cv: 5